Update example-workflow.yml

diff --git a/.github/workflows/example-workflow.yml b/.github/workflows/example-workflow.yml
--- a/.github/workflows/example-workflow.yml
+++ b/.github/workflows/example-workflow.yml
@@ -64,6 +64,7 @@ jobs:
         id: not-bypass
         run: |
           echo "::error ::Action not skipped, needs.check-bypass.outputs.can-skip is ${{ needs.check-bypass.outputs.can-skip }}"
+          exit 1
 
   test-action-bypass:
     needs: check-bypass
@@ -74,4 +75,6 @@ jobs:
     steps:
       - name: Action Skipped
         id: bypass
-        run: echo "::error ::Action skipped"
+        run: |
+          echo "::error ::Action skipped"
+          exit 1
