Update example-workflow.yml

diff --git a/.github/workflows/example-workflow.yml b/.github/workflows/example-workflow.yml
--- a/.github/workflows/example-workflow.yml
+++ b/.github/workflows/example-workflow.yml
@@ -62,7 +62,9 @@ jobs:
     steps:
       - name: Action Not Skipped
         id: not-bypass
-        run: echo "::error ::Action not skipped, needs.check-bypass.outputs.can-skip is ${{ needs.check-bypass.outputs.can-skip }}"
+        run: ｜
+          echo "::error ::Action not skipped, needs.check-bypass.outputs.can-skip is ${{ needs.check-bypass.outputs.can-skip }}"
+          exit 1
 
   test-action-bypass:
     needs: check-bypass
